# Generated by Django 4.0.3 on 2022-03-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doc_etc', models.ManyToManyField(blank=True, related_name='etc_funds', to='test1.document')),
                ('doc_fund_registration', models.ManyToManyField(blank=True, related_name='registration_funds', to='test1.document')),
            ],
        ),
    ]
