# Generated by Django 4.0.3 on 2022-03-20 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('account_bank', models.CharField(choices=[('H', 'Hana'), ('K', 'KB')], max_length=1)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='test1.fund')),
            ],
        ),
    ]
